name: Protect Main

on:
  pull_request:
    branches:
      - main

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check source branch
        run: |
          if [ "${{ github.head_ref }}" != "development" ]; then
            echo "Only development can be merged into main."
            exit 1
          fi